In [ ]:
# A university moniters electricity usage (in units) of 4 hostels over 7 days (Monday to Sunday).
# The data is stored in a 2D list as shown below:


In [7]:
# Task A1: 
# Create a NumPy array electricity using np.random.randint:
# Values between 120 and 650
# Shape (4, 7)
import numpy as np
electricity = np.random.randint(120, 651, size=(4, 7)) 
print("Electricity usage (units) of 4 hostels over 7 days:\n", electricity)


Electricity usage (units) of 4 hostels over 7 days:
 [[376 297 146 534 204 472 614]
 [182 178 399 172 532 364 203]
 [139 624 291 520 531 644 439]
 [524 365 397 257 297 245 578]]


In [8]:
# Task A2:
# Print the following attributes of the array:
# Shape, Number of dimensions, Total number of elements, and Data type.
print("Shape of the array:", electricity.shape)
print("Number of dimensions:", electricity.ndim)
print("Total number of elements:", electricity.size)
print("Data type of the elements:", electricity.dtype)

Shape of the array: (4, 7)
Number of dimensions: 2
Total number of elements: 28
Data type of the elements: int32


In [11]:
# Task B1: Hostel wise Metrics
# Find the average electricity usage per hostel, the maximum usage per hostel, and identify hostel has the highest average usage.
average_usage_per_hostel = np.mean(electricity, axis=1)
max_usage_per_hostel = np.max(electricity, axis=1)
hostel_with_highest_average = np.argmax(average_usage_per_hostel)
print("\nAverage electricity usage per hostel:", average_usage_per_hostel)
print("Maximum electricity usage per hostel:", max_usage_per_hostel)
print("Hostel with highest average usage:", hostel_with_highest_average)


Average electricity usage per hostel: [377.57142857 290.         455.42857143 380.42857143]
Maximum electricity usage per hostel: [614 532 644 578]
Hostel with highest average usage: 2


In [10]:
# Task B2: Day wise Metrics
# Calculate the total electricity consumption for each day and identify the day with the highest total campus consumption.
# Requirment: Students must choose the correct axis values for each operation.
total_consumption_per_day = np.sum(electricity, axis=0)
day_with_highest_consumption = np.argmax(total_consumption_per_day)
print("\nTotal electricity consumption per day:", total_consumption_per_day)
print("Day with the highest total campus consumption (0-indexed):", day_with_highest_consumption)


Total electricity consumption per day: [1221 1464 1233 1483 1564 1725 1834]
Day with the highest total campus consumption (0-indexed): 6


In [15]:
# PART C - BROADCASTING & POLICY RULES
# Policy Rule: If electricity usage on any day is greater than 550 units, a 20 % surcharge is applied.
# Task C1
# Create a new array penalized_usage such that:
# Values > 550 -> multiplied by 1.20
# All other values remain unchanged.
# Constraints: Must use np.where. No loops allowed.
penalized_usage = np.where(electricity > 550, electricity * 1.20, electricity)
print("\nPenalized electricity usage (with surcharge applied where applicable):\n", penalized_usage)


Penalized electricity usage (with surcharge applied where applicable):
 [[376.  297.  146.  534.  204.  472.  736.8]
 [182.  178.  399.  172.  532.  364.  203. ]
 [139.  748.8 291.  520.  531.  772.8 439. ]
 [524.  365.  397.  257.  297.  245.  693.6]]


In [16]:
#  PART D - COMPARATIVE ANALYSIS
# Task D1: Thinking Task
# Compare each hostel's daily usage with its own weekly average. Create a boolean matrix where:
# True: Above hostel average
# False: Below or equal to hostel average
# Requirement: Requires broadcasting of a (4,) array across a(4, 7) array.
above_average_usage = electricity > average_usage_per_hostel[:, np.newaxis]
print("\nBoolean matrix indicating above average usage per hostel:\n", above_average_usage)


Boolean matrix indicating above average usage per hostel:
 [[False False False  True False  True  True]
 [False False  True False  True  True False]
 [False  True False  True  True  True False]
 [ True False  True False False False  True]]


In [17]:
# PART E - RESHAPING & DATA STRUCTURE
# Task E1: Reshape the electricity data into a single row representing weekly usage (Shape 1x28).
reshaped_electricity = electricity.reshape(1, -1)
print("\nReshaped electricity data (1x28):\n", reshaped_electricity)


Reshaped electricity data (1x28):
 [[376 297 146 534 204 472 614 182 178 399 172 532 364 203 139 624 291 520
  531 644 439 524 365 397 257 297 245 578]]


In [18]:
# Task E2
# Reshape the same data into 2 rows and 14 columns.Ensure no data is lost or duplicated.
reshaped_electricity_2 = electricity.reshape(2, 14)
print("\nReshaped electricity data (2x14):\n", reshaped_electricity_2)


Reshaped electricity data (2x14):
 [[376 297 146 534 204 472 614 182 178 399 172 532 364 203]
 [139 624 291 520 531 644 439 524 365 397 257 297 245 578]]


In [20]:
# PART F - MEMORY SAFETY
# Task F1: Copy vs View
# Create ref_backup=electricity
# Create safe_backup=electricity.copy()
# Modify one value in the original electricity array.
# Observe which backups change.
# Explaination Reuired: Why is ref_backup risky? Why is safe_backup safer?
ref_backup = electricity
safe_backup = electricity.copy()
# Modify one value in the original electricity array
electricity[0, 0] = 999
print("\nOriginal electricity array after modification:\n", electricity)
print("\nReference backup (ref_backup):\n", ref_backup)
print("\nSafe backup (safe_backup):\n", safe_backup)


Original electricity array after modification:
 [[999 297 146 534 204 472 614]
 [182 178 399 172 532 364 203]
 [139 624 291 520 531 644 439]
 [524 365 397 257 297 245 578]]

Reference backup (ref_backup):
 [[999 297 146 534 204 472 614]
 [182 178 399 172 532 364 203]
 [139 624 291 520 531 644 439]
 [524 365 397 257 297 245 578]]

Safe backup (safe_backup):
 [[999 297 146 534 204 472 614]
 [182 178 399 172 532 364 203]
 [139 624 291 520 531 644 439]
 [524 365 397 257 297 245 578]]
