In [1]:
# 2D Indexing
import numpy as np
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0, 1])
print(mat[1]) 

2
[4 5 6]


In [2]:
print(mat[:, 1])

[2 5 8]


In [ ]:
a=np.array([1,2,3])
b=a.copy()  #copy
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [ ]:
a=np.array([1,2,3])
b=a  #this logic is not safe
b[0]=99
print(a)

[99  2  3]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

#scalar operations
print(a+10)
print(a*2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[11 12 13]
[2 4 6]


In [9]:
# unfus(Universal functions)
a=np.array([1, 4, 9, 16])
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.sum(a))
print(np.std(a))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [11]:
# Boolean Indexing
arr=np.array([10,20,30,40,50])
print(arr>25)
print(arr[arr>25])

[False False  True  True  True]
[30 40 50]


In [5]:
# Broadcasting Rules

import numpy as np
arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [6]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [7]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


In [8]:
# Matrix Multiplication

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [9]:
print(A.T)  #transpose

[[1 3]
 [2 4]]


In [ ]:
# Random Module
np.random.rand(5)

array([0.32123948, 0.08536665, 0.05821801, 0.28289051, 0.04202057])

In [13]:
np.random.randn(3,3)

array([[ 2.12350407,  0.05717594, -0.20748246],
       [-0.31139287, -1.32363004,  0.84069714],
       [-1.26927829,  0.8113781 , -0.6299092 ]])

In [ ]:
np.random.randint(1, 100, 10)  #10 random integers between 1 and 100 and 10 is the number of elements

array([66, 82, 73, 59, 54, 92, 39, 66, 53, 72], dtype=int32)

In [ ]:
# Reshaping Arrays
# It will change the shape of array without changing its data
arr=np.arange(12) 
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Axis in Numpy

import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
print(np.sum(arr))

21


In [ ]:
print(np.sum(arr, axis=0))  #column wise sum. It will give us the sum of each column.

[5 7 9]


In [ ]:
print(np.sum(arr, axis=1))  #column wise sum. It will give us the sum of each row.

[ 6 15]


In [ ]:
# Where in Numpy

arr=np.array([10, -5, 20, -3, 15])
result=np.where(arr<0, 0, arr)  #if condition is true then 0 else arr. It will replace all negative values with 0 and keep positive values as they are.
print(result)

[10  0 20  0 15]


In [ ]:
arr=np.array([1, 2, 3, 4, 5])
result=np.where(arr%2!=0, -1,arr)  #if condition is true then 'Even' else 'Odd'. -1 is for odd and even is for even numbers
print(result)

[-1  2 -1  4 -1]


In [31]:
marks=np.array([45, 78, 32, 90, 55])
status=np.where(marks>=50, 1, 0)  #if condition is true then 1 else 0. 1 is for pass and 0 is for fail
print(status)

[0 1 0 1 1]


In [32]:
data=np.array([10, 20, 30, 40, 50])
mean_value=np.mean(data)
result=np.where(data>mean_value, mean_value, data)  #if data value is greater than mean then replace it with mean else keep it as it is
print(result)

[10. 20. 30. 30. 30.]


In [33]:
# Applying (where) condition in 2D array

mat=np.array([[10, 60, 30], [80, 20, 90]])
result=np.where(mat>50, 1, 0)  #if condition is true then 1 else 0. 1 is for values greater than 50 and 0 is for values less than or equal to 50.
print(result)

[[0 1 0]
 [1 0 1]]
