In [1]:
# Task 1.1 Create 1D array called cost price3 items [1500, 3000, 5000]
# Task 1.2 Create 2D array called daily sales [[10, 15, 8, 12], [5, 7, 4, 6], [2, 3, 2, 4]]
# Task 1.2 Print the shape and dimension of both arrays
import numpy as np
cost = np.array([1500, 3000, 5000])
daily_sales = np.array([[10, 15, 8, 12], [5, 7, 4, 6], [2, 3, 2, 4]])
print("Cost price array:", cost)
print("Daily sales array:\n", daily_sales)
print("Shape of cost price array:", cost.shape)
print("Dimension of cost price array:", cost.ndim)
print("Shape of daily sales array:", daily_sales.shape)
print("Dimension of daily sales array:", daily_sales.ndim)

Cost price array: [1500 3000 5000]
Daily sales array:
 [[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]
Shape of cost price array: (3,)
Dimension of cost price array: 1
Shape of daily sales array: (3, 4)
Dimension of daily sales array: 2


In [2]:
#  Task 2.1 (Grace Units)
# The manager decides to add **2 "bonus" units** to the daily sales of each item. Update the `daily_sales` array accordingly and print the updated array.
daily_sales += 2
print("Updated daily sales with bonus units:\n", daily_sales)

Updated daily sales with bonus units:
 [[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [3]:
#  Task 2.2 (Revenue)
# Calculate the total revenue for each day, 
# 1- Multiplying the cost_price with the total daily_sales matrix. 
# 2- Observe how numpy handles the multiplication of 1D and 2D arrays. give code
total_revenue = np.dot(cost, daily_sales)
print("Total revenue for each day:", total_revenue)

Total revenue for each day: [59000 77500 53000 75000]


In [4]:
# Task 2.3 (Scaling)
# Use np.sqrt() on the sales data to find the square root of all sales values for a statistical curve.
sqrt_sales = np.sqrt(daily_sales)
print("Square root of daily sales:\n", sqrt_sales)

Square root of daily sales:
 [[3.46410162 4.12310563 3.16227766 3.74165739]
 [2.64575131 3.         2.44948974 2.82842712]
 [2.         2.23606798 2.         2.44948974]]


In [5]:
# Task 3.1 
# Access the sales data for Smartwatches (Row 1) for all 4 days and print it.
smartwatch_sales = daily_sales[1, :]
print("Sales data for Smartwatches (Row 1):")
print(smartwatch_sales)

Sales data for Smartwatches (Row 1):
[7 9 6 8]


In [6]:
# Task 3.2
# Access the sales data for all products for the first two days (Monday and Tuesday). Print the resulting array.
first_two_days_sales = daily_sales[:, :2]
print("Sales data for all products for the first two days (Monday and Tuesday):")
print(first_two_days_sales)

Sales data for all products for the first two days (Monday and Tuesday):
[[12 17]
 [ 7  9]
 [ 4  5]]


In [7]:
# Task 3.3
# Access the sale of Speakers on Thursday specially using double indexing and print it.
speakers_thursday_sales = daily_sales[2, 3]
print("Sales of Speakers on Thursday:", speakers_thursday_sales)

Sales of Speakers on Thursday: 6


In [8]:
# Task 3.4
# Using slicing, extract a 2x2 sub-array representing the sales of Headphones and Smartwaches for Monday and Tuesday.
headphones_smartwatches_monday_tuesday = daily_sales[0:2, 0:2]
print("Sales of Headphones and Smartwatches for Monday and Tuesday:\n", headphones_smartwatches_monday_tuesday)

Sales of Headphones and Smartwatches for Monday and Tuesday:
 [[12 17]
 [ 7  9]]


In [9]:
# Task 4.1
# Flatten the 3x4 `daily_sales` array into a 1D array 12 elements using .reshape() and print the result.
flattened_sales = daily_sales.reshape(-1)
print("Flattened sales data (1D array with 12 elements):")
print(flattened_sales)

Flattened sales data (1D array with 12 elements):
[12 17 10 14  7  9  6  8  4  5  4  6]


In [10]:
# Task 4.2
# Convert the sales data into a 2x6 matrix.
sales_2x6 = daily_sales.reshape(2, 6)
print("Sales data converted into a 2x6 matrix:")
print(sales_2x6)

Sales data converted into a 2x6 matrix:
[[12 17 10 14  7  9]
 [ 6  8  4  5  4  6]]


In [11]:
# Task 4.3
# Use np.linspace to create an array of 10 equal intervals between 0 and 100 to represent "Discount Percentages".
discount_percentages = np.linspace(0, 100, 10)
print("Discount Percentages (10 equal intervals between 0 and 100):")
print(discount_percentages)

Discount Percentages (10 equal intervals between 0 and 100):
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [12]:
# Task 5.1
# Use np.random.randint to generate a new 3x4 array of "Pridicted Sales" for the next week with values ranging from 0 to 20.
predicted_sales = np.random.randint(0, 21, size=(3, 4))
print("Predicted Sales for the next week (3x4 array with values from 0 to 20):\n", predicted_sales)

Predicted Sales for the next week (3x4 array with values from 0 to 20):
 [[14  2  8 16]
 [ 3  0 20 14]
 [19 18 12 15]]


In [13]:
# Task 5.2
# Generate a random array of 5 numbers between 0 and 1 using np.random.rand.
random_numbers = np.random.rand(5)
print("Random numbers between 0 and 1:", random_numbers)

Random numbers between 0 and 1: [0.42470418 0.15708982 0.40801456 0.30175986 0.48138256]


In [14]:
# Task 5.3 (Challenge)
# Use np.sum() to find :
# 1- Total items sold over all 4 days.
# 2- Total items sold for each product (Sum across rows).
total_items_sold = np.sum(daily_sales)
total_items_sold_per_product = np.sum(daily_sales, axis=1)
print("Total items sold over all 4 days:", total_items_sold)
print("Total items sold for each product (Sum across rows):", total_items_sold_per_product)

Total items sold over all 4 days: 102
Total items sold for each product (Sum across rows): [53 30 19]
