In [1]:
# The system tracks 5 students across 3 subjects (out of 100):
# S1: [78, 85, 90], S2: [45, 60, 55], S3: [88, 92, 95], S4: [30, 40, 35], S5: [65, 70, 75]
# Task: Initialize this data as a 2D NumPy array named marks.
import numpy as np
marks = np.array([[78, 85, 90],
                  [45, 60, 55],
                  [88, 92, 95],
                  [30, 40, 35],
                  [65, 70, 75]])
print(marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [2]:
# Task A1: Metadata Discovery
# Determine the Shape of the array.
# Find the Total Number of elements.
# Identify the Data Type of the elements. give code for all three tasks
print("Shape of the array:", marks.shape)
print("Total number of elements:", marks.size)

Shape of the array: (5, 3)
Total number of elements: 15


In [3]:
# Task A2: Data Indexing & Slicing
# Extract all marks for the 2nd student.
# Extract all marks for the 3rd subject across all students.
# Find the specific mark for Student 1 in Student 2. give code for all three tasks
student_2_marks = marks[1]
print("Marks for Student 2:", student_2_marks)
subject_3_marks = marks[:, 2]
print("Marks for Subject 3 across all students:", subject_3_marks)
student_1_subject_2_mark = marks[0, 1]
print("Mark for Student 1 in Subject 2:", student_1_subject_2_mark)

Marks for Student 2: [45 60 55]
Marks for Subject 3 across all students: [90 55 95 35 75]
Mark for Student 1 in Subject 2: 85


In [4]:
# Task B1: Means and Averages
# Calculate the average marks for each student.
# Calculate the average marks for each subject.
# Hint: Think about the axis parameter.
average_marks_per_student = np.mean(marks, axis=1)
print("Average marks for each student:", average_marks_per_student)
average_marks_per_subject = np.mean(marks, axis=0)
print("Average marks for each subject:", average_marks_per_subject)

Average marks for each student: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Average marks for each subject: [61.2 69.4 70. ]


In [5]:
# Task B2: Filtering Top Performers
# Identify and display students whose average marks are >=80.
top_performers = average_marks_per_student >= 80
print("Top performers (average marks >= 80):", top_performers)

Top performers (average marks >= 80): [ True False  True False False]


In [6]:
# Task B3: Global Adjustments
# The college decides to add 5 grace marks to every subject for every student. Update the array using broadcasting.
marks += 5
print("Updated marks after adding grace marks:\n", marks)

Updated marks after adding grace marks:
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [7]:
# Task C1: Pass / Fail Mapping
# Create a status matrix where 
# Marks >= 50 -> 1 (Pass)
# Marks < 50 -> 0 (Fail)
status_matrix = np.where(marks >= 50, 1, 0)
print("Pass/Fail status matrix:\n", status_matrix)

Pass/Fail status matrix:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [8]:
# Task C2: Data Cleaning
# To standardize failing grades, replace all marks below 40 with a value of 0.
marks[marks < 40] = 0
print("Marks after cleaning (replacing marks < 40 with 0):\n", marks)

Marks after cleaning (replacing marks < 40 with 0):
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [  0  45  40]
 [ 70  75  80]]


In [9]:
# Task D1: Grade Allocation Apply a grading system based on the Student Average:
# Avg >= 85: Grade A (Score: 10)
# Avg >= 70: Grade B (Score: 8)
# Avg >= 50: Grade C (Score: 6)
# Below 50:  No Grade (Score: 0)
# Requirment: Use nested conditional logic within NumPy.
average_marks_per_student = np.mean(marks, axis=1)
grades = np.where(average_marks_per_student >= 85, 10,
            np.where(average_marks_per_student >= 70, 8,
            np.where(average_marks_per_student >= 50, 6, 0)))
print("Grades based on average marks:\n", grades)

Grades based on average marks:
 [10  6 10  0  8]


In [10]:
# Task E1: The "Copy vs View" Challenge
# Create a backup of the marks array.
# Modify the original array (e.g., setmarks[0, 0]=0).
# Check if the backup array changed or remained original.
# Disscussion Question: Why is it dangerous to use backup = marks instead of backup = marks.copy()?
backup = marks.copy()
marks[0, 0] = 0
print("Original marks after modification:\n", marks)
print("Backup marks (should remain unchanged):\n", backup)
# Discussion: Using backup = marks creates a reference to the same array, so any changes to marks will also affect backup. Using backup = marks.copy() creates a separate copy of the array, ensuring that changes to marks do not affect backup.

Original marks after modification:
 [[  0  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [  0  45  40]
 [ 70  75  80]]
Backup marks (should remain unchanged):
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [  0  45  40]
 [ 70  75  80]]
